# PIPELINE DEFINITION
# Name: hello-world-pipeline
# Description: A simple Hello World Vertex AI pipeline.
# Inputs:
#    name: str [Default: 'World']
components:
  comp-hello-world-component:
    executorLabel: exec-hello-world-component
    inputDefinitions:
      parameters:
        name:
          parameterType: STRING
    outputDefinitions:
      parameters:
        Output:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-hello-world-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - hello_world_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.15.2'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef hello_world_component(name: str) -> str:\n    greeting = f\"\
          Hello, {name}!\"\n    print(greeting)\n    return greeting\n\n"
        image: python:3.11
pipelineInfo:
  description: A simple Hello World Vertex AI pipeline.
  name: hello-world-pipeline
root:
  dag:
    tasks:
      hello-world-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-hello-world-component
        inputs:
          parameters:
            name:
              componentInputParameter: name
        taskInfo:
          name: hello-world-component
  inputDefinitions:
    parameters:
      name:
        defaultValue: World
        isOptional: true
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.15.2
