# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Linting"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          enable-cache: true
          cache-dependency-glob: |
            ./pyproject.toml
            ./uv.lock

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.54.0

      - name: Init TFLint
        run: |
          cp .tflint.hcl ~
          tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install dependencies
        run: |
          uv sync --group tools

      - name: Boilerplate
        id: boilerplate
        run: |
          uv run python tools/check_boilerplate.py $GITHUB_WORKSPACE

      - name: Terraform Linting Check
        id: fmt
        run: |
          terraform fmt -recursive -check -diff $GITHUB_WORKSPACE

      - name: TFLint
        run: cd cloud-run-single && tflint --recursive -f compact

      - name: Check documentation
        id: documentation
        run: |
          uv run python tools/check_documentation.py . \
            --show-diffs \
            --no-show-summary

      - name: Check documentation links
        id: documentation-links
        run: |
          uv run python tools/check_links.py . \
            --no-show-summary \
            --exclude ./ai-apps-conversational/1-apps/data/ds-kb

      - name: Check python formatting
        id: yapf
        run: |
          uv run yapf . \
            --parallel \
            --diff \
            --recursive 
